name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Extract version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Install PostgreSQL 16
      run: |
        # Add PostgreSQL APT repository
        sudo apt-get update
        sudo apt-get install -y wget ca-certificates
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
        
        # Update and install PostgreSQL
        sudo apt-get update
        sudo apt-get install -y postgresql-16 postgresql-server-dev-16 postgresql-client-16
        
        # Start PostgreSQL
        sudo systemctl start postgresql
        sudo systemctl enable postgresql
        
        # Configure PostgreSQL
        sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"
        sudo -u postgres createdb test_db
    
    - name: Install build dependencies
      run: |
        sudo apt-get install -y build-essential
    
    - name: Build and test extension
      run: |
        export PG_CONFIG=/usr/lib/postgresql/16/bin/pg_config
        make clean
        make
        sudo make install
        make installcheck PGUSER=postgres PGDATABASE=test_db
      env:
        PGPASSWORD: postgres
    
    - name: Create distribution package
      run: |
        mkdir -p dist
        # Create a clean copy for distribution
        rsync -av --exclude='.git*' --exclude='dist' --exclude='*.o' --exclude='*.so' . dist/hashlib-${{ steps.version.outputs.VERSION }}/
        cd dist
        zip -r hashlib-${{ steps.version.outputs.VERSION }}.zip hashlib-${{ steps.version.outputs.VERSION }}/
        tar -czf hashlib-${{ steps.version.outputs.VERSION }}.tar.gz hashlib-${{ steps.version.outputs.VERSION }}/
    
    - name: Generate checksums
      run: |
        cd dist
        sha256sum hashlib-${{ steps.version.outputs.VERSION }}.zip > hashlib-${{ steps.version.outputs.VERSION }}.zip.sha256
        sha256sum hashlib-${{ steps.version.outputs.VERSION }}.tar.gz > hashlib-${{ steps.version.outputs.VERSION }}.tar.gz.sha256
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ steps.version.outputs.VERSION }}
        draft: false
        prerelease: false
        generate_release_notes: true
        files: |
          dist/hashlib-${{ steps.version.outputs.VERSION }}.zip
          dist/hashlib-${{ steps.version.outputs.VERSION }}.tar.gz
          dist/hashlib-${{ steps.version.outputs.VERSION }}.zip.sha256
          dist/hashlib-${{ steps.version.outputs.VERSION }}.tar.gz.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 